using AngleSharp.Dom;
using AngleSharp.Html.Parser;

namespace ForgeTrust.Runnable.Web.RazorDocs.Services;

/// <summary>
/// Rewrites harvested documentation links so authored Markdown can use repository-relative source links while the
/// rendered docs experience still navigates through canonical RazorDocs routes.
/// </summary>
internal static class DocContentLinkRewriter
{
    private const string DocsFrameId = "doc-content";

    /// <summary>
    /// Rewrites internal documentation anchors in rendered HTML so they point at canonical RazorDocs routes and carry
    /// Turbo navigation attributes that keep browser history aligned with frame navigation.
    /// </summary>
    /// <param name="sourcePath">The harvested source path whose content is being rewritten.</param>
    /// <param name="html">The rendered and sanitized HTML fragment to rewrite.</param>
    /// <param name="targetManifest">Manifest of harvested documentation targets that may be rewritten to docs routes.</param>
    /// <returns>The rewritten HTML fragment.</returns>
    internal static string RewriteInternalDocLinks(
        string sourcePath,
        string html,
        DocLinkTargetManifest targetManifest)
    {
        return RewriteInternalDocLinks(sourcePath, html, "/docs", targetManifest);
    }

    /// <summary>
    /// Rewrites internal documentation anchors in rendered HTML so they point at canonical RazorDocs routes and carry
    /// Turbo navigation attributes that keep browser history aligned with frame navigation.
    /// </summary>
    /// <param name="sourcePath">The harvested source path whose content is being rewritten.</param>
    /// <param name="html">The rendered and sanitized HTML fragment to rewrite.</param>
    /// <param name="docsRootPath">The app-relative docs root path that should own rewritten links.</param>
    /// <param name="targetManifest">Manifest of harvested documentation targets that may be rewritten to docs routes.</param>
    /// <returns>The rewritten HTML fragment.</returns>
    internal static string RewriteInternalDocLinks(
        string sourcePath,
        string html,
        string docsRootPath,
        DocLinkTargetManifest targetManifest)
    {
        ArgumentNullException.ThrowIfNull(sourcePath);
        ArgumentNullException.ThrowIfNull(html);
        ArgumentException.ThrowIfNullOrWhiteSpace(docsRootPath);
        ArgumentNullException.ThrowIfNull(targetManifest);

        if (html.IndexOf("<a", StringComparison.OrdinalIgnoreCase) < 0)
        {
            return html;
        }

        var parser = new HtmlParser();
        var document = parser.ParseDocument(html);
        foreach (var anchor in document.QuerySelectorAll("a[href]"))
        {
            RewriteAnchorElement(sourcePath, docsRootPath, anchor, targetManifest);
        }

        return document.Body?.InnerHtml ?? html;
    }

    /// <summary>
    /// Prefixes request <c>PathBase</c> for rooted docs-local anchor hrefs in rendered HTML content.
    /// </summary>
    /// <param name="html">The rendered HTML fragment whose rooted docs-local links should honor the current request path base.</param>
    /// <param name="docsRootPath">The current live docs root that owns source-backed documentation routes.</param>
    /// <param name="requestPathBase">The request path base that should prefix rooted docs-local hrefs when present.</param>
    /// <returns>
    /// The original fragment when no path base applies or no docs-local rooted links are present; otherwise a fragment
    /// whose docs-local anchor hrefs are prefixed so mounted apps stay inside their virtual root.
    /// </returns>
    /// <remarks>
    /// This helper intentionally scopes itself to docs-local routes rather than all rooted links. Authored content may
    /// legitimately include other site-rooted links that should remain outside the docs shell, while docs-local links
    /// generated by <see cref="RewriteInternalDocLinks(string,string,string,DocLinkTargetManifest)"/> must stay within
    /// the current mounted app.
    /// </remarks>
    internal static string PrefixPathBaseForDocsUrls(string html, string docsRootPath, string? requestPathBase)
    {
        ArgumentNullException.ThrowIfNull(html);
        ArgumentException.ThrowIfNullOrWhiteSpace(docsRootPath);

        if (string.IsNullOrWhiteSpace(requestPathBase)
            || string.Equals(requestPathBase, "/", StringComparison.Ordinal)
            || html.IndexOf("<a", StringComparison.OrdinalIgnoreCase) < 0)
        {
            return html;
        }

        var normalizedPathBase = NormalizePathBase(requestPathBase);
        var parser = new HtmlParser();
        var document = parser.ParseDocument(html);
        foreach (var anchor in document.QuerySelectorAll("a[href]"))
        {
            PrefixDocsHrefWithPathBase(anchor, docsRootPath, normalizedPathBase);
        }

        return document.Body?.InnerHtml ?? html;
    }

    private static void RewriteAnchorElement(
        string sourcePath,
        string docsRootPath,
        IElement anchor,
        DocLinkTargetManifest targetManifest)
    {
        if (HasNonSelfTarget(anchor))
        {
            return;
        }

        var href = anchor.GetAttribute("href");
        if (!TryBuildDocsHref(sourcePath, href, docsRootPath, targetManifest, out var docsHref))
        {
            return;
        }

        anchor.SetAttribute("href", docsHref);
        anchor.SetAttribute("data-turbo-frame", DocsFrameId);
        anchor.SetAttribute("data-turbo-action", "advance");

        if (docsHref.Contains('#'))
        {
            anchor.SetAttribute("data-doc-anchor-link", "true");
        }
    }

    private static bool HasNonSelfTarget(IElement anchor)
    {
        var target = anchor.GetAttribute("target")?.Trim();
        return !string.IsNullOrWhiteSpace(target)
               && !string.Equals(target, "_self", StringComparison.OrdinalIgnoreCase);
    }

    private static void PrefixDocsHrefWithPathBase(IElement anchor, string docsRootPath, string requestPathBase)
    {
        var href = anchor.GetAttribute("href");
        if (!TryBuildPathBaseAwareDocsHref(anchor, href, docsRootPath, requestPathBase, out var pathBaseAwareHref))
        {
            return;
        }

        anchor.SetAttribute("href", pathBaseAwareHref);
    }

    private static bool TryBuildDocsHref(
        string sourcePath,
        string? href,
        string docsRootPath,
        DocLinkTargetManifest targetManifest,
        out string docsHref)
    {
        docsHref = string.Empty;
        if (string.IsNullOrWhiteSpace(href))
        {
            return false;
        }

        var trimmedHref = href.Trim();
        var (path, query, fragment) = SplitHref(trimmedHref);

        if (string.Equals(path, docsRootPath, StringComparison.OrdinalIgnoreCase))
        {
            docsHref = docsRootPath + query + fragment;
            return true;
        }

        if (DocsUrlBuilder.IsUnderRoot(path, docsRootPath)
            && !string.Equals(path, docsRootPath, StringComparison.OrdinalIgnoreCase))
        {
            var docsRelativePath = string.Equals(docsRootPath, "/", StringComparison.Ordinal)
                ? path.TrimStart('/')
                : path[(docsRootPath.Length + 1)..];
            if (!targetManifest.Contains(docsRelativePath))
            {
                return false;
            }

            docsHref = BuildDocsHref(docsRootPath, docsRelativePath, query, fragment);
            return true;
        }

        if (trimmedHref.StartsWith('#'))
        {
            if (!targetManifest.Contains(sourcePath))
            {
                return false;
            }

            docsHref = DocsUrlBuilder.BuildDocUrl(
                           docsRootPath,
                           DocRoutePath.BuildCanonicalPath(GetSourceDocumentPath(sourcePath)))
                       + fragment;
            return true;
        }

        if (trimmedHref.StartsWith("//", StringComparison.Ordinal))
        {
            return false;
        }

        if (string.IsNullOrWhiteSpace(path))
        {
            return false;
        }

        if (path.StartsWith("/", StringComparison.Ordinal))
        {
            var rootedTarget = path.TrimStart('/');
            if (!targetManifest.Contains(rootedTarget))
            {
                return false;
            }

            docsHref = BuildDocsHref(docsRootPath, rootedTarget, query, fragment);
            return true;
        }

        if (Uri.TryCreate(trimmedHref, UriKind.Absolute, out _))
        {
            return false;
        }

        var resolvedTarget = ResolveRelativePath(sourcePath, path);
        if (!targetManifest.Contains(resolvedTarget))
        {
            return false;
        }

        docsHref = BuildDocsHref(docsRootPath, resolvedTarget, query, fragment);
        return true;
    }

    private static string BuildDocsHref(string docsRootPath, string docPath, string query, string fragment)
    {
        return DocsUrlBuilder.BuildDocUrl(docsRootPath, DocRoutePath.BuildCanonicalPath(docPath)) + query + fragment;
    }

    private static bool TryBuildPathBaseAwareDocsHref(
        IElement anchor,
        string? href,
        string docsRootPath,
        string requestPathBase,
        out string pathBaseAwareHref)
    {
        pathBaseAwareHref = string.Empty;
        if (string.IsNullOrWhiteSpace(href))
        {
            return false;
        }

        var trimmedHref = href.Trim();
        if (trimmedHref.StartsWith("//", StringComparison.Ordinal)
            || trimmedHref.StartsWith('#'))
        {
            return false;
        }

        var (path, _, _) = SplitHref(trimmedHref);
        if (!path.StartsWith("/", StringComparison.Ordinal)
            && Uri.TryCreate(trimmedHref, UriKind.Absolute, out _))
        {
            return false;
        }

        if (!path.StartsWith("/", StringComparison.Ordinal)
            || (!IsDocsLocalRootedPath(path, docsRootPath)
                && !IsRootMountedDecoratedDocsLink(anchor, docsRootPath, path)))
        {
            return false;
        }

        pathBaseAwareHref = requestPathBase + trimmedHref;
        return true;
    }

    private static bool IsDocsLocalRootedPath(string path, string docsRootPath)
    {
        return DocsUrlBuilder.IsUnderRoot(path, docsRootPath)
               || DocsUrlBuilder.IsUnderRoot(path, DocsUrlBuilder.DocsEntryPath)
               || DocsUrlBuilder.IsUnderRoot(path, DocsUrlBuilder.DocsVersionsPath)
               || string.Equals(path, DocsUrlBuilder.DocsVersionPrefix, StringComparison.OrdinalIgnoreCase)
               || path.StartsWith(DocsUrlBuilder.DocsVersionPrefix + "/", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsRootMountedDecoratedDocsLink(IElement anchor, string docsRootPath, string path)
    {
        if (!string.Equals(docsRootPath, "/", StringComparison.Ordinal)
            || !path.StartsWith("/", StringComparison.Ordinal))
        {
            return false;
        }

        var usesDocsFrame = string.Equals(anchor.GetAttribute("data-turbo-frame"), DocsFrameId, StringComparison.OrdinalIgnoreCase)
                            && string.Equals(anchor.GetAttribute("data-turbo-action"), "advance", StringComparison.OrdinalIgnoreCase);
        var isDocsAnchorLink = string.Equals(anchor.GetAttribute("data-doc-anchor-link"), "true", StringComparison.OrdinalIgnoreCase);
        return usesDocsFrame || isDocsAnchorLink;
    }

    private static string NormalizePathBase(string requestPathBase)
    {
        var normalizedPathBase = requestPathBase.Trim();
        if (!normalizedPathBase.StartsWith("/", StringComparison.Ordinal))
        {
            normalizedPathBase = "/" + normalizedPathBase;
        }

        return normalizedPathBase.TrimEnd('/');
    }

    private static string ResolveRelativePath(string sourcePath, string relativePath)
    {
        var normalizedSourcePath = GetSourceDocumentPath(sourcePath).Replace('\\', '/').Trim('/');
        var sourceDirectory = Path.GetDirectoryName(normalizedSourcePath)?.Replace('\\', '/');
        var basePath = string.IsNullOrWhiteSpace(sourceDirectory)
            ? "/"
            : "/" + sourceDirectory.Trim('/') + "/";
        var baseUri = new Uri(new Uri("http://docs.local"), basePath);
        var resolvedUri = new Uri(baseUri, relativePath);
        return resolvedUri.AbsolutePath.TrimStart('/');
    }

    private static string GetSourceDocumentPath(string sourcePath)
    {
        var hashIndex = sourcePath.IndexOf('#');
        return hashIndex >= 0 ? sourcePath[..hashIndex] : sourcePath;
    }

    private static (string Path, string Query, string Fragment) SplitHref(string href)
    {
        var fragmentIndex = href.IndexOf('#');
        var fragment = fragmentIndex >= 0 ? href[fragmentIndex..] : string.Empty;
        var withoutFragment = fragmentIndex >= 0 ? href[..fragmentIndex] : href;
        var queryIndex = withoutFragment.IndexOf('?');
        var query = queryIndex >= 0 ? withoutFragment[queryIndex..] : string.Empty;
        var path = queryIndex >= 0 ? withoutFragment[..queryIndex] : withoutFragment;
        return (path, query, fragment);
    }
}
