using Ganss.Xss;

namespace ForgeTrust.Runnable.Web.RazorDocs.Services;

/// <summary>
/// RazorDocs-specific HTML sanitizer configuration.
/// </summary>
internal sealed class RazorDocsHtmlSanitizer : IRazorDocsHtmlSanitizer
{
    internal HtmlSanitizer InnerSanitizer { get; } = CreateSanitizer();

    public string Sanitize(string html)
    {
        ArgumentNullException.ThrowIfNull(html);
        return InnerSanitizer.Sanitize(html);
    }

    private static HtmlSanitizer CreateSanitizer()
    {
        var sanitizer = new HtmlSanitizer();

        // Preserve semantic API markup and anchor targets generated by harvesters.
        foreach (var tag in new[] { "section", "article", "header", "details", "summary" })
        {
            sanitizer.AllowedTags.Add(tag);
        }

        foreach (var attribute in new[] { "class", "id", "open" })
        {
            sanitizer.AllowedAttributes.Add(attribute);
        }

        return sanitizer;
    }
}
