<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <DefineConstants>$(DefineConstants);APP_SURFACE_TAILWIND_TASKS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../ForgeTrust.AppSurface.Web.Tailwind/Internal/**/*.cs" Link="Internal/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ForgeTrust.AppSurface.Web.Tailwind.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Build.Framework">
      <HintPath>$(MSBuildToolsPath)/Microsoft.Build.Framework.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Build.Utilities.Core">
      <HintPath>$(MSBuildToolsPath)/Microsoft.Build.Utilities.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
