using ForgeTrust.Runnable.Web.RazorDocs.Models;
using ForgeTrust.Runnable.Web.RazorDocs.Services;
using Ganss.Xss;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;

namespace ForgeTrust.Runnable.Web.RazorDocs;

/// <summary>
/// Registers RazorDocs services and typed options.
/// </summary>
public static class RazorDocsServiceCollectionExtensions
{
    /// <summary>
    /// Adds the RazorDocs package services and options to the service collection.
    /// </summary>
    /// <param name="services">The target service collection.</param>
    /// <returns>The same service collection for chaining.</returns>
    public static IServiceCollection AddRazorDocs(this IServiceCollection services)
    {
        services.AddOptions<RazorDocsOptions>()
            .BindConfiguration(RazorDocsOptions.SectionName)
            .PostConfigure<IConfiguration>(
                (options, configuration) =>
                {
                    options.Source ??= new RazorDocsSourceOptions();
                    options.Bundle ??= new RazorDocsBundleOptions();
                    options.Sidebar ??= new RazorDocsSidebarOptions();
                    options.Sidebar.NamespacePrefixes ??= [];

                    if (options.Source.RepositoryRoot is null)
                    {
                        options.Source.RepositoryRoot = NormalizeOrNull(configuration["RepositoryRoot"]);
                    }
                    else
                    {
                        options.Source.RepositoryRoot = options.Source.RepositoryRoot.Trim();
                    }

                    options.Bundle.Path = NormalizeOrNull(options.Bundle.Path);
                    options.Sidebar.NamespacePrefixes = options.Sidebar.NamespacePrefixes
                        .Where(prefix => !string.IsNullOrWhiteSpace(prefix))
                        .Select(prefix => prefix.Trim())
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .ToArray();
                })
            .ValidateOnStart();

        services.TryAddEnumerable(
            ServiceDescriptor.Singleton<IValidateOptions<RazorDocsOptions>, RazorDocsOptionsValidator>());
        services.TryAddSingleton(sp => sp.GetRequiredService<IOptions<RazorDocsOptions>>().Value);

        services.TryAddSingleton<IHtmlSanitizer>(
            _ =>
            {
                var sanitizer = new HtmlSanitizer();

                // Preserve semantic API markup and anchor targets generated by harvesters.
                foreach (var tag in new[] { "section", "article", "header", "details", "summary" })
                {
                    sanitizer.AllowedTags.Add(tag);
                }

                foreach (var attribute in new[] { "class", "id", "open" })
                {
                    sanitizer.AllowedAttributes.Add(attribute);
                }

                return sanitizer;
            });
        services.TryAddEnumerable(ServiceDescriptor.Singleton<IDocHarvester, MarkdownHarvester>());
        services.TryAddEnumerable(ServiceDescriptor.Singleton<IDocHarvester, CSharpDocHarvester>());
        services.TryAddSingleton<DocAggregator>();

        return services;
    }

    private static string? NormalizeOrNull(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        return value.Trim();
    }
}
