using ForgeTrust.Runnable.Core;
using ForgeTrust.Runnable.Caching;
using ForgeTrust.Runnable.Web.RazorWire;
using ForgeTrust.Runnable.Web.RazorDocs.Models;
using ForgeTrust.Runnable.Web.RazorDocs.Services;
using Ganss.Xss;

namespace ForgeTrust.Runnable.Web.RazorDocs;

/// <summary>
/// Web module configuration for the RazorDocs documentation system.
/// </summary>
public class RazorDocsWebModule : IRunnableWebModule
{
    /// <inheritdoc />
    public bool IncludeAsApplicationPart => true;

    /// <summary>
    /// Registers services required by the RazorDocs module into the provided service collection.
    /// </summary>
    /// <remarks>
    /// Adds HTML sanitizer, Markdown and C# harvesters, and the documentation aggregator.
    /// </remarks>
    public void ConfigureServices(StartupContext context, IServiceCollection services)
    {
        services.AddSingleton<IHtmlSanitizer>(
            _ =>
            {
                var sanitizer = new HtmlSanitizer();

                // Preserve semantic API markup and anchor targets generated by harvesters.
                foreach (var tag in new[] { "section", "article", "header", "details", "summary" })
                {
                    sanitizer.AllowedTags.Add(tag);
                }

                foreach (var attribute in new[] { "class", "id", "open" })
                {
                    sanitizer.AllowedAttributes.Add(attribute);
                }

                return sanitizer;
            });
        services.AddSingleton<IDocHarvester, MarkdownHarvester>();
        services.AddSingleton<IDocHarvester, CSharpDocHarvester>();
        services.AddSingleton<DocAggregator>();
    }

    /// <summary>
    /// Registers runtime module dependencies for this web module, including RazorWireWebModule.
    /// </summary>
    /// <param name="builder">The dependency builder used to register required modules.</param>
    public void RegisterDependentModules(ModuleDependencyBuilder builder)
    {
        builder.AddModule<RunnableCachingModule>();
        builder.AddModule<RazorWireWebModule>();
    }

    /// <summary>
    /// Performs host-level configuration steps before application services are registered.
    /// </summary>
    /// <param name="context">The startup context providing module and environment information.</param>
    /// <param name="builder">The host builder to configure prior to service registration.</param>
    public void ConfigureHostBeforeServices(StartupContext context, IHostBuilder builder)
    {
    }

    /// <summary>
    /// Performs host-level configuration steps after application services have been registered.
    /// </summary>
    /// <param name="context">The startup context providing module and environment information.</param>
    /// <param name="builder">The host builder to modify or extend after services are configured.</param>
    public void ConfigureHostAfterServices(StartupContext context, IHostBuilder builder)
    {
    }

    /// <summary>
    /// Configures the application's request pipeline and middleware for this module.
    /// </summary>
    /// <param name="context">The startup context for the module invocation.</param>
    /// <param name="app">The application builder used to configure middleware and endpoints.</param>
    public void ConfigureWebApplication(StartupContext context, IApplicationBuilder app)
    {
    }

    /// <summary>
    /// Adds the module's default catch-all controller route for documentation endpoints.
    /// </summary>
    /// <param name="context">Startup context for the application and environment.</param>
    /// <param name="endpoints">Endpoint route builder used to map the module's routes.</param>
    public void ConfigureEndpoints(StartupContext context, IEndpointRouteBuilder endpoints)
    {
        // Index route MUST come before catch-all to be matched first
        endpoints.MapControllerRoute(
            name: "razordocs_index",
            pattern: "docs",
            defaults: new
            {
                controller = "Docs",
                action = "Index"
            });

        endpoints.MapControllerRoute(
            name: "razordocs_search",
            pattern: "docs/search",
            defaults: new
            {
                controller = "Docs",
                action = "Search"
            });

        endpoints.MapControllerRoute(
            name: "razordocs_search_index",
            pattern: "docs/search-index.json",
            defaults: new
            {
                controller = "Docs",
                action = "SearchIndex"
            });

        endpoints.MapControllerRoute(
            name: "razordocs_doc",
            pattern: "docs/{*path}",
            defaults: new
            {
                controller = "Docs",
                action = "Details"
            });

        // Maintain fallback for legacy if necessary, but preferred is /docs
        endpoints.MapControllerRoute(
            name: "razordocs_default",
            pattern: "{controller=Docs}/{action=Index}/{path?}");
    }
}
