ignore:
  - "Aspire/ForgeTrust.Runnable.Aspire.Tests/**"
  - "Caching/ForgeTrust.Runnable.Caching.Tests/**"
  - "Config/ForgeTrust.Runnable.Config.Tests/**"
  - "Console/ForgeTrust.Runnable.Console.Tests/**"
  - "ForgeTrust.Runnable.Core.Tests/**"
  - "Web/ForgeTrust.Runnable.Web.RazorDocs.Tests/**"
  - "Web/ForgeTrust.Runnable.Web.RazorWire.Cli.Tests/**"
  - "Web/ForgeTrust.Runnable.Web.RazorWire.IntegrationTests/**"
  - "Web/ForgeTrust.Runnable.Web.RazorWire.Tests/**"
  - "Web/ForgeTrust.Runnable.Web.Tailwind.Tests/**"
  - "Web/ForgeTrust.Runnable.Web.Tests/**"
  - "Web/ForgeTrust.Runnable.Web.Tests.SharedErrorPagesFixture/**"
  - "Web/ForgeTrust.Runnable.Web.RazorDocs/wwwroot/docs/**"
