using Ganss.Xss;

namespace ForgeTrust.AppSurface.Docs.Services;

/// <summary>
/// Sanitizes harvested AppSurface Docs HTML with the package-owned allowlist for docs content and highlighted code blocks.
/// </summary>
/// <remarks>
/// AppSurface Docs starts from the HtmlSanitizer defaults, adds the package-owned content tags <c>section</c>,
/// <c>article</c>, <c>header</c>, <c>details</c>, <c>summary</c>, <c>pre</c>, <c>code</c>, and <c>span</c>, and
/// allows the <c>class</c>, <c>id</c>, <c>open</c>, <c>role</c>, <c>aria-label</c>, and package-owned rich-authoring and code
/// <c>data-*</c> attributes. The
/// sanitizer explicitly removes <c>style</c> from the default attribute set so harvested Markdown, generated API HTML,
/// and server-side highlighted code can keep structural hooks while inline presentation and unsafe markup are stripped.
/// Callers should pass already-rendered AppSurface Docs HTML through this sanitizer before display or export; supported
/// semantic wrappers and token spans are preserved, while scripts, event handlers, inline styles, and unsupported
/// attributes are discarded.
/// </remarks>
internal sealed class AppSurfaceDocsHtmlSanitizer : IAppSurfaceDocsHtmlSanitizer
{
    internal HtmlSanitizer InnerSanitizer { get; } = CreateSanitizer();

    /// <summary>
    /// Sanitizes rendered documentation HTML using the AppSurface Docs allowlist.
    /// </summary>
    /// <param name="html">The rendered HTML to sanitize.</param>
    /// <returns>Safe HTML that preserves AppSurface Docs structural markup and removes unsupported tags or attributes.</returns>
    public string Sanitize(string html)
    {
        ArgumentNullException.ThrowIfNull(html);
        return InnerSanitizer.Sanitize(html);
    }

    private static HtmlSanitizer CreateSanitizer()
    {
        var sanitizer = new HtmlSanitizer();

        // Preserve semantic API markup and anchor targets generated by harvesters.
        foreach (var tag in new[] { "section", "article", "header", "details", "summary", "pre", "code", "span" })
        {
            sanitizer.AllowedTags.Add(tag);
        }

        foreach (var attribute in new[]
                 {
                     "class",
                     "id",
                     "open",
                     "role",
                     "aria-label",
                     "data-doc-code-language",
                     "data-appsurfacedocs-rich",
                     "data-appsurfacedocs-rich-tabs",
                     "data-appsurfacedocs-rich-tabs-baseline",
                     "data-appsurfacedocs-rich-tab-panel",
                     "data-appsurfacedocs-rich-tab-label",
                     "data-appsurfacedocs-rich-tabs-token"
                 })
        {
            sanitizer.AllowedAttributes.Add(attribute);
        }

        sanitizer.AllowedAttributes.Remove("style");

        return sanitizer;
    }
}
