<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="GitHubActionsTestLogger">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Config\ForgeTrust.AppSurface.Config.GoogleSecretManager\ForgeTrust.AppSurface.Config.GoogleSecretManager.csproj" />
    <ProjectReference Include="..\..\Durable\ForgeTrust.AppSurface.Durable.PostgreSql\ForgeTrust.AppSurface.Durable.PostgreSql.csproj" />
    <ProjectReference Include="..\..\Evidence\ForgeTrust.AppSurface.Evidence.Cli\ForgeTrust.AppSurface.Evidence.Cli.csproj" />
    <ProjectReference Include="..\..\Evidence\ForgeTrust.AppSurface.Evidence.Contracts\ForgeTrust.AppSurface.Evidence.Contracts.csproj" />
    <ProjectReference Include="..\..\Evidence\ForgeTrust.AppSurface.Evidence.Planner\ForgeTrust.AppSurface.Evidence.Planner.csproj" />
    <ProjectReference Include="..\ForgeTrust.AppSurface.Cli\ForgeTrust.AppSurface.Cli.csproj" />
    <ProjectReference Include="..\..\tests\ForgeTrust.AppSurface.Testing\ForgeTrust.AppSurface.Testing.csproj" />
  </ItemGroup>

</Project>
