using System.Globalization;
using System.Security.Cryptography;
using System.Text.Json;
using System.Xml;
using System.Xml.Linq;
#if !EVIDENCE_COVERAGE_CORE
using ForgeTrust.AppSurface.CoverageArtifacts;
#endif

#if EVIDENCE_COVERAGE_CORE
using CommandException = ForgeTrust.AppSurface.Evidence.Coverage.CoverageExecutionException;
#endif

#if EVIDENCE_COVERAGE_CORE
namespace ForgeTrust.AppSurface.Evidence.Coverage;
#else
namespace ForgeTrust.AppSurface.Cli;
#endif

/// <summary>
/// Coverage integrations supported by the VSTest-based <c>coverage run</c> workflow.
/// </summary>
internal enum CoverageRunDriver
{
    /// <summary>
    /// Use the in-process Coverlet VSTest data collector.
    /// </summary>
    Collector,

    /// <summary>
    /// Use the legacy Coverlet MSBuild task integration.
    /// </summary>
    Msbuild,
}

/// <summary>
/// Describes one driver's raw and canonical artifact locations for a project invocation.
/// </summary>
/// <param name="Driver">The single driver selected for the run.</param>
/// <param name="ProjectOutputDirectory">The AppSurface-owned canonical directory for this project.</param>
/// <param name="RawResultsDirectory">The unique collector attachment directory, or <see langword="null"/> for MSBuild.</param>
/// <param name="OwnedArguments">Arguments generated by AppSurface that callers must not override.</param>
internal sealed record CoverageRunDriverInvocation(
    CoverageRunDriver Driver,
    string ProjectOutputDirectory,
    string? RawResultsDirectory,
    IReadOnlyList<string> OwnedArguments);

/// <summary>
/// Result of normalizing one driver's current-invocation coverage artifact.
/// </summary>
/// <param name="Status">
/// Stable artifact outcome: <c>produced</c>, <c>missing</c>, <c>multiple</c>,
/// <c>unreadable</c>, <c>escaping</c>, or <c>malformed</c>.
/// </param>
/// <param name="CoverageFile">Canonical absolute Cobertura path when <paramref name="Status"/> is <c>produced</c>.</param>
/// <param name="Cause">Stable diagnostic detail for a non-produced outcome, otherwise <see langword="null"/>.</param>
/// <param name="CleanupDiagnostic">Best-effort staged-file cleanup warning that did not change the primary normalization outcome.</param>
internal sealed record CoverageRunDriverNormalization(
    string Status,
    string? CoverageFile,
    string? Cause = null,
    string? CleanupDiagnostic = null);

/// <summary>
/// Validates VSTest engine and direct package capabilities before coverage output is mutated.
/// </summary>
internal static class CoverageRunDriverPreflight
{
    /// <summary>
    /// Validates the selected engine and every selected project's evaluated coverage package.
    /// </summary>
    /// <param name="driver">The requested VSTest coverage driver.</param>
    /// <param name="configuration">The evaluated build configuration.</param>
    /// <param name="resolution">The resolved solution and selected test projects.</param>
    /// <param name="processRunner">Runner used for supervised MSBuild capability queries.</param>
    /// <param name="supervisor">Run-scoped supervisor for discovery operations and cancellation.</param>
    /// <param name="cancellationToken">Cancellation token for capability evaluation.</param>
    /// <returns>A task that completes when every project is compatible.</returns>
    /// <remarks>Throws a stable coverage execution diagnostic for an engine incompatibility or aggregated project package and capability failures in stable project order.</remarks>
    public static async Task ValidateAsync(
        CoverageRunDriver driver,
        string configuration,
        CoverageProjectResolution resolution,
        ICoverageRunProcessRunner processRunner,
        CoverageRunWatchdogSupervisor supervisor,
        CancellationToken cancellationToken)
    {
        ValidateEngine(resolution.SolutionDirectory);
        var requiredPackage = driver == CoverageRunDriver.Collector ? "coverlet.collector" : "coverlet.msbuild";
        var failures = new List<string>();

        foreach (var project in resolution.Projects)
        {
            var result = await EvaluateCapabilitiesAsync(
                project,
                configuration,
                targetFramework: null,
                resolution.SolutionDirectory,
                processRunner,
                supervisor,
                cancellationToken);

            if (result.ExitCode != 0
                || result.StandardOutput is null
                || !TryReadCapabilities(
                    result.StandardOutput,
                    requiredPackage,
                    out var hasPackage,
                    out var hasDuplicatePackage,
                    out var usesMtp,
                    out var targetFrameworks,
                    out var requiresPerFrameworkEvaluation))
            {
                failures.Add($"{project.RelativePath}: capability evaluation failed");
                continue;
            }

            if (hasDuplicatePackage)
            {
                failures.Add($"{project.RelativePath}: duplicate direct {requiredPackage}; fix: remove the duplicate PackageReference");
                continue;
            }

            if (targetFrameworks.Count == 0)
            {
                var failureCount = failures.Count;
                AddCapabilityFailure(project.RelativePath, hasPackage, usesMtp, driver, requiredPackage, failures);
                if (failures.Count == failureCount)
                {
                    failures.Add($"{project.RelativePath}: capability evaluation returned no TargetFramework or TargetFrameworks");
                }

                continue;
            }

            if (!requiresPerFrameworkEvaluation)
            {
                AddCapabilityFailure(project.RelativePath, hasPackage, usesMtp, driver, requiredPackage, failures);
                continue;
            }

            foreach (var targetFramework in targetFrameworks)
            {
                var innerResult = await EvaluateCapabilitiesAsync(
                    project,
                    configuration,
                    targetFramework,
                    resolution.SolutionDirectory,
                    processRunner,
                    supervisor,
                    cancellationToken);
                if (innerResult.ExitCode != 0
                    || innerResult.StandardOutput is null
                    || !TryReadCapabilities(innerResult.StandardOutput, requiredPackage, out var innerHasPackage, out var innerHasDuplicatePackage, out var innerUsesMtp, out _, out _))
                {
                    failures.Add($"{project.RelativePath} [{targetFramework}]: capability evaluation failed");
                    continue;
                }

                if (innerHasDuplicatePackage)
                {
                    failures.Add($"{project.RelativePath} [{targetFramework}]: duplicate direct {requiredPackage}; fix: remove the duplicate PackageReference");
                    continue;
                }

                AddCapabilityFailure($"{project.RelativePath} [{targetFramework}]", innerHasPackage, innerUsesMtp, driver, requiredPackage, failures);
            }
        }

        if (failures.Count > 0)
        {
            throw CoverageRunDiagnostics.Create(
                "ASCOV113",
                $"Coverage driver '{DriverName(driver)}' is unavailable for one or more selected projects.",
                string.Join("; ", failures),
                $"Add {requiredPackage} to every selected VSTest project, or choose the compatible driver explicitly.",
                "Cli/ForgeTrust.AppSurface.Cli/README.md#coverage-driver-selection");
        }
    }

    private static async Task<CoverageRunProcessResult> EvaluateCapabilitiesAsync(
        CoverageRunProject project,
        string configuration,
        string? targetFramework,
        string solutionDirectory,
        ICoverageRunProcessRunner processRunner,
        CoverageRunWatchdogSupervisor supervisor,
        CancellationToken cancellationToken)
    {
        var args = new List<string>
        {
            "msbuild",
            project.FullPath,
            "-getItem:PackageReference",
            "-getProperty:TestingPlatformDotnetTestSupport,TargetFramework,TargetFrameworks",
            $"-property:Configuration={configuration}",
            "-nologo",
        };
        if (targetFramework is not null)
        {
            args.Insert(args.Count - 1, $"-property:TargetFramework={targetFramework}");
        }

        using var operation = supervisor.Start("discovery", project.RelativePath, commandOptions: ["msbuild", "-getItem", "-getProperty", "-nologo"]);
        try
        {
            return await processRunner.RunAsync(
                new CoverageRunProcessRequest("dotnet", args, solutionDirectory, null, operation.ObserveBytes, operation.ReserveProcess()),
                cancellationToken);
        }
        catch (OperationCanceledException)
        {
            supervisor.ThrowIfFailed();
            throw;
        }
    }

    private static void AddCapabilityFailure(
        string projectLabel,
        bool hasPackage,
        bool usesMtp,
        CoverageRunDriver driver,
        string requiredPackage,
        List<string> failures)
    {
        if (usesMtp)
        {
            failures.Add($"{projectLabel}: TestingPlatformDotnetTestSupport=true requires coverlet.MTP, not the VSTest {DriverName(driver)} driver");
        }
        else if (!hasPackage)
        {
            failures.Add($"{projectLabel}: missing direct {requiredPackage}; fix: dotnet add {Quote(projectLabel.Split(" [", 2, StringSplitOptions.None)[0])} package {requiredPackage}");
        }
    }

    private static void ValidateEngine(string solutionDirectory)
    {
        var globalJson = FindNearestGlobalJson(solutionDirectory);
        if (globalJson is null)
        {
            return;
        }

        try
        {
            using var stream = File.OpenRead(globalJson);
            using var document = JsonDocument.Parse(stream, new JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = JsonCommentHandling.Skip,
            });
            if (document.RootElement.ValueKind != JsonValueKind.Object)
            {
                throw IncompatibleEngine(globalJson, "malformed root object");
            }

            if (!document.RootElement.TryGetProperty("test", out var test))
            {
                return;
            }

            if (test.ValueKind != JsonValueKind.Object)
            {
                throw IncompatibleEngine(globalJson, "malformed test configuration");
            }

            if (!test.TryGetProperty("runner", out var runner))
            {
                return;
            }

            var value = runner.ValueKind == JsonValueKind.String ? runner.GetString() : null;
            if (string.Equals(value, "VSTest", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            throw IncompatibleEngine(globalJson, string.IsNullOrWhiteSpace(value) ? $"malformed runner ({runner.ValueKind})" : value);
        }
        catch (JsonException ex)
        {
            throw IncompatibleEngine(globalJson, $"malformed JSON ({ex.GetType().Name})");
        }
        catch (IOException ex)
        {
            throw IncompatibleEngine(globalJson, $"unreadable global.json ({ex.GetType().Name})");
        }
        catch (UnauthorizedAccessException ex)
        {
            throw IncompatibleEngine(globalJson, $"unreadable global.json ({ex.GetType().Name})");
        }
    }

    private static string? FindNearestGlobalJson(string startDirectory)
    {
        for (var directory = new DirectoryInfo(Path.GetFullPath(startDirectory)); directory is not null; directory = directory.Parent)
        {
            var candidate = Path.Join(directory.FullName, "global.json");
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }

        return null;
    }

    private static Exception IncompatibleEngine(string path, string runner)
        => CoverageRunDiagnostics.Create(
            "ASCOV113",
            "The selected coverage driver requires VSTest.",
            $"{path} selects unsupported test runner '{runner}'.",
            "Use VSTest for collector or msbuild mode; native Microsoft Testing Platform coverage requires coverlet.MTP and is outside #672.",
            "Cli/ForgeTrust.AppSurface.Cli/README.md#coverage-driver-selection");

    private static bool TryReadCapabilities(
        string json,
        string requiredPackage,
        out bool hasPackage,
        out bool hasDuplicatePackage,
        out bool usesMtp,
        out IReadOnlyList<string> targetFrameworks,
        out bool requiresPerFrameworkEvaluation)
    {
        hasPackage = false;
        hasDuplicatePackage = false;
        usesMtp = false;
        targetFrameworks = [];
        requiresPerFrameworkEvaluation = false;
        try
        {
            using var document = JsonDocument.Parse(json);
            if (!document.RootElement.TryGetProperty("Properties", out var properties)
                || !document.RootElement.TryGetProperty("Items", out var items)
                || !items.TryGetProperty("PackageReference", out var packageReferences)
                || packageReferences.ValueKind != JsonValueKind.Array)
            {
                return false;
            }

            if (properties.ValueKind != JsonValueKind.Object)
            {
                return false;
            }

            if (properties.TryGetProperty("TestingPlatformDotnetTestSupport", out var mtpProperty))
            {
                usesMtp = mtpProperty.ValueKind == JsonValueKind.String
                    && string.Equals(mtpProperty.GetString(), "true", StringComparison.OrdinalIgnoreCase);
            }

            if (properties.TryGetProperty("TargetFrameworks", out var targetFrameworksProperty)
                && targetFrameworksProperty.ValueKind == JsonValueKind.String
                && !string.IsNullOrWhiteSpace(targetFrameworksProperty.GetString()))
            {
                targetFrameworks = targetFrameworksProperty.GetString()!
                    .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                requiresPerFrameworkEvaluation = true;
            }
            else if (properties.TryGetProperty("TargetFramework", out var targetFrameworkProperty)
                && targetFrameworkProperty.ValueKind == JsonValueKind.String
                && !string.IsNullOrWhiteSpace(targetFrameworkProperty.GetString()))
            {
                targetFrameworks = [targetFrameworkProperty.GetString()!.Trim()];
            }

            var matches = packageReferences.EnumerateArray()
                .Count(item => item.ValueKind == JsonValueKind.Object
                    && item.TryGetProperty("Identity", out var identity)
                    && identity.ValueKind == JsonValueKind.String
                    && string.Equals(identity.GetString(), requiredPackage, StringComparison.OrdinalIgnoreCase));
            hasPackage = matches == 1;
            hasDuplicatePackage = matches > 1;
            return true;
        }
        catch (JsonException)
        {
            return false;
        }
    }

    /// <summary>
    /// Returns the stable lowercase CLI name for a coverage driver.
    /// </summary>
    /// <param name="driver">The coverage driver value.</param>
    /// <returns><c>collector</c> or <c>msbuild</c>.</returns>
    internal static string DriverName(CoverageRunDriver driver) => driver.ToString().ToLowerInvariant();

    private static string Quote(string value) => value.Contains(' ', StringComparison.Ordinal) ? $"\"{value}\"" : value;
}

/// <summary>
/// Owns coverage-driver arguments and deterministic per-project artifact normalization.
/// </summary>
internal static class CoverageRunDriverStrategy
{
    private static readonly XmlReaderSettings ReaderSettings = new()
    {
        Async = true,
        DtdProcessing = DtdProcessing.Prohibit,
        XmlResolver = null,
    };

    /// <summary>
    /// Validates user arguments that would override AppSurface-owned coverage behavior.
    /// </summary>
    /// <param name="driver">The driver whose reserved arguments should be enforced.</param>
    /// <param name="arguments">User-supplied <c>dotnet test</c> arguments in invocation order.</param>
    /// <remarks>Throws a stable coverage execution diagnostic when an argument collides with driver-owned coverage configuration.</remarks>
    public static void ValidateTestArguments(CoverageRunDriver driver, IReadOnlyList<string> arguments)
    {
        for (var index = 0; index < arguments.Count; index++)
        {
            var argument = arguments[index];
            if (driver == CoverageRunDriver.Collector
                && (string.Equals(argument, "--collect", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(argument, "--results-directory", StringComparison.OrdinalIgnoreCase))
                && index + 1 >= arguments.Count)
            {
                throw CoverageRunDiagnostics.Create(
                    "ASCOV101",
                    "--test-argument contains an incomplete owned option.",
                    $"'{argument}' requires a value but AppSurface owns that setting.",
                    "Remove the option and use the coverage run driver contract.",
                    "Cli/ForgeTrust.AppSurface.Cli/README.md#coverage-driver-selection");
            }

            if (IsOwnedMsbuildPropertyArgument(argument)
                || driver == CoverageRunDriver.Collector
                && (argument == "--"
                    || argument.StartsWith("DataCollectionRunSettings.", StringComparison.OrdinalIgnoreCase)
                    || IsSettingsArgument(argument)
                    || IsOwnedCollectorJoinedArgument(argument)
                    || IsOwnedCollectorSplitArgument(argument)))
            {
                throw CoverageRunDiagnostics.Create(
                    "ASCOV101",
                    "--test-argument cannot override AppSurface-owned coverage settings.",
                    $"The {CoverageRunDriverPreflight.DriverName(driver)} driver owns token '{argument}'.",
                    "Remove the coverage, results-directory, or runsettings override and use the dedicated coverage run options.",
                    "Cli/ForgeTrust.AppSurface.Cli/README.md#coverage-driver-selection");
            }
        }
    }

    /// <summary>
    /// Creates driver-owned arguments and raw artifact locations for one project invocation.
    /// </summary>
    /// <param name="request">The validated coverage-run request.</param>
    /// <param name="projectOutputDirectory">Absolute AppSurface-owned output directory for the project.</param>
    /// <returns>The driver invocation, including its unique collector directory when applicable.</returns>
    /// <remarks>Throws a stable coverage execution diagnostic when a generated collector invocation directory collides with an existing filesystem object.</remarks>
    public static CoverageRunDriverInvocation CreateInvocation(
        CoverageRunRequest request,
        string projectOutputDirectory)
    {
        if (request.CoverageDriver == CoverageRunDriver.Msbuild)
        {
            var canonical = Path.Join(projectOutputDirectory, "coverage.cobertura.xml");
            if (File.Exists(canonical))
            {
                File.Delete(canonical);
            }

            var args = new List<string>
            {
                "/p:CollectCoverage=true",
                $"/p:CoverletOutput={Path.Join(projectOutputDirectory, "coverage")}",
                "/p:CoverletOutputFormat=cobertura",
            };
            if (!string.IsNullOrWhiteSpace(request.IncludeFilter))
            {
                args.Add($"/p:Include={request.IncludeFilter.Replace(",", "%2c", StringComparison.Ordinal)}");
            }

            if (!string.IsNullOrWhiteSpace(request.ExcludeFilter))
            {
                args.Add($"/p:Exclude={request.ExcludeFilter.Replace(",", "%2c", StringComparison.Ordinal)}");
            }

            return new CoverageRunDriverInvocation(request.CoverageDriver, projectOutputDirectory, null, args);
        }

        var runId = RandomNumberGenerator.GetHexString(32).ToLowerInvariant();
        var rawResultsDirectory = Path.Join(projectOutputDirectory, "collector-results", runId);
        if (Directory.Exists(rawResultsDirectory) || File.Exists(rawResultsDirectory))
        {
            throw ArtifactFailure(projectOutputDirectory, rawResultsDirectory, "invocation directory collision");
        }

        Directory.CreateDirectory(rawResultsDirectory);
        var collectorArgs = new List<string>
        {
            "--collect:XPlat Code Coverage",
            "--results-directory",
            Path.GetFullPath(rawResultsDirectory),
        };
        return new CoverageRunDriverInvocation(request.CoverageDriver, projectOutputDirectory, rawResultsDirectory, collectorArgs);
    }

    /// <summary>
    /// Appends collector runsettings after user-controlled pre-separator arguments.
    /// </summary>
    /// <param name="request">The validated coverage-run request.</param>
    /// <param name="arguments">Mutable <c>dotnet test</c> argument list to complete.</param>
    public static void AppendCollectorRunSettings(CoverageRunRequest request, List<string> arguments)
    {
        if (request.CoverageDriver != CoverageRunDriver.Collector)
        {
            return;
        }

        arguments.Add("--");
        arguments.Add("DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura");
        if (!string.IsNullOrWhiteSpace(request.IncludeFilter))
        {
            arguments.Add($"DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Include={request.IncludeFilter}");
        }

        if (!string.IsNullOrWhiteSpace(request.ExcludeFilter))
        {
            arguments.Add($"DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude={request.ExcludeFilter}");
        }
    }

    /// <summary>
    /// Normalizes the current invocation's driver artifact into the canonical project path.
    /// </summary>
    /// <param name="invocation">The driver invocation and its artifact locations.</param>
    /// <param name="processExitCode">Exit code from the corresponding <c>dotnet test</c> process.</param>
    /// <param name="logFile">Project log path included in artifact diagnostics.</param>
    /// <param name="cancellationToken">Cancellation token for artifact inspection and staging.</param>
    /// <param name="commitGate">Optional gate that must authorize canonical artifact replacement.</param>
    /// <returns><see langword="true"/> when the current invocation produced a canonical artifact; otherwise <see langword="false"/>.</returns>
    /// <remarks>Throws a stable coverage execution diagnostic when a successful test process produces an invalid artifact result.</remarks>
    public static async Task<bool> NormalizeAsync(
        CoverageRunDriverInvocation invocation,
        int processExitCode,
        string logFile,
        CancellationToken cancellationToken,
        Action<Action>? commitGate = null)
    {
        var result = await NormalizeDetailedAsync(invocation, cancellationToken, commitGate);
        if (result.Cause is not null && processExitCode == 0)
        {
            throw ArtifactFailure(logFile, invocation.RawResultsDirectory ?? invocation.ProjectOutputDirectory, result.Cause);
        }

        return result.Status == "produced";
    }

    /// <summary>
    /// Normalizes an artifact and returns a stable status without selecting the run's primary failure.
    /// </summary>
    /// <param name="invocation">The driver invocation and its artifact locations.</param>
    /// <param name="cancellationToken">Cancellation token for artifact inspection and staging.</param>
    /// <param name="commitGate">Optional gate that must authorize canonical artifact replacement.</param>
    /// <param name="beforeArtifactOpen">Optional test seam invoked after candidate discovery and before the artifact is opened.</param>
    /// <param name="deleteStagedFile">Optional test seam that replaces deletion of the staged coverage file.</param>
    /// <returns>A stable normalization status and the canonical absolute artifact path only when produced.</returns>
    public static async Task<CoverageRunDriverNormalization> NormalizeDetailedAsync(
        CoverageRunDriverInvocation invocation,
        CancellationToken cancellationToken,
        Action<Action>? commitGate = null,
        Action? beforeArtifactOpen = null,
        Action<string>? deleteStagedFile = null)
    {
        var canonical = Path.Join(invocation.ProjectOutputDirectory, "coverage.cobertura.xml");
        if (invocation.Driver == CoverageRunDriver.Msbuild)
        {
            return File.Exists(canonical)
                ? new CoverageRunDriverNormalization("produced", canonical)
                : new CoverageRunDriverNormalization("missing", null, "zero Cobertura files");
        }

        var rawDirectory = invocation.RawResultsDirectory!;
        string[] candidates;
        try
        {
            candidates = EnumerateCollectorArtifacts(rawDirectory);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or CoverageRunArtifactContractException)
        {
            return ex is CoverageRunArtifactContractException contract
                ? new CoverageRunDriverNormalization(contract.Status, null, contract.Cause)
                : new CoverageRunDriverNormalization("unreadable", null, $"unreadable raw results ({ex.GetType().Name})");
        }

        if (candidates.Length != 1)
        {
            return candidates.Length == 0
                ? new CoverageRunDriverNormalization("missing", null, "zero Cobertura files")
                : new CoverageRunDriverNormalization("multiple", null, $"multiple Cobertura files ({candidates.Length})");
        }

        string? staged = null;
        string? cleanupDiagnostic = null;
        try
        {
            var candidate = candidates[0];
            ValidatePhysicalContainment(rawDirectory, candidate);
            beforeArtifactOpen?.Invoke();
            staged = Path.Join(invocation.ProjectOutputDirectory, $".coverage.{Guid.NewGuid():N}.tmp");
            try
            {
                await using (var output = new FileStream(staged, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true))
                await using (var input = CoverageRunArtifactReader.OpenRegularFile(
                    invocation.ProjectOutputDirectory,
                    rawDirectory,
                    candidate))
                {
                    await input.CopyToAsync(output, cancellationToken);
                    await output.FlushAsync(cancellationToken);
                }

                await using (var stagedInput = new FileStream(staged, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true))
                using (var reader = XmlReader.Create(stagedInput, ReaderSettings))
                {
                    var document = await XDocument.LoadAsync(reader, LoadOptions.None, cancellationToken);
                    if (!string.Equals(document.Root?.Name.LocalName, "coverage", StringComparison.Ordinal))
                    {
                        throw new InvalidDataException("The root element is not coverage.");
                    }
                }

                cancellationToken.ThrowIfCancellationRequested();
                if (commitGate is null)
                {
                    File.Move(staged, canonical, overwrite: true);
                }
                else
                {
                    commitGate(() => File.Move(staged, canonical, overwrite: true));
                }
            }
            finally
            {
                if (staged is { } stagedFile && File.Exists(stagedFile))
                {
                    try
                    {
                        (deleteStagedFile ?? File.Delete)(stagedFile);
                    }
                    catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                    {
                        cleanupDiagnostic = $"ASCOV123 Staged coverage artifact cleanup failed. Cause: {ex.GetType().Name}. The primary normalization outcome was retained; a temporary .coverage file may remain.";
                    }
                }
            }

            return new CoverageRunDriverNormalization("produced", canonical, CleanupDiagnostic: cleanupDiagnostic);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or XmlException or InvalidDataException or CoverageRunArtifactContractException)
        {
            if (ex is CoverageRunArtifactContractException contract)
            {
                return new CoverageRunDriverNormalization(contract.Status, null, contract.Cause, cleanupDiagnostic);
            }

            var malformed = ex is XmlException or InvalidDataException;
            return new CoverageRunDriverNormalization(
                malformed ? "malformed" : "unreadable",
                null,
                $"{(malformed ? "malformed" : "unreadable")} Cobertura ({ex.GetType().Name})",
                cleanupDiagnostic);
        }
    }

    private static string[] EnumerateCollectorArtifacts(string rawDirectory)
    {
        if (!Directory.Exists(rawDirectory))
        {
            return [];
        }

        var candidates = new List<string>();
        var pending = new Stack<string>();
        pending.Push(Path.GetFullPath(rawDirectory));
        while (pending.TryPop(out var directory))
        {
            foreach (var entry in Directory.EnumerateFileSystemEntries(directory, "*", SearchOption.TopDirectoryOnly))
            {
                var attributes = File.GetAttributes(entry);
                if ((attributes & FileAttributes.ReparsePoint) != 0)
                {
                    throw new CoverageRunArtifactContractException("escaping", "symbolic link or reparse point encountered");
                }

                if ((attributes & FileAttributes.Directory) != 0)
                {
                    pending.Push(entry);
                }
                else if (string.Equals(Path.GetFileName(entry), "coverage.cobertura.xml", StringComparison.Ordinal))
                {
                    candidates.Add(Path.GetFullPath(entry));
                }
            }
        }

        return candidates.OrderBy(path => path, GetPathComparer()).ToArray();
    }

    private static void ValidatePhysicalContainment(string root, string candidate)
    {
        var rootPath = Path.GetFullPath(root);
        var candidatePath = Path.GetFullPath(candidate);
        var comparison = OperatingSystem.IsWindows() || OperatingSystem.IsMacOS()
            ? StringComparison.OrdinalIgnoreCase
            : StringComparison.Ordinal;
        if (!candidatePath.StartsWith(Path.EndsInDirectorySeparator(rootPath) ? rootPath : rootPath + Path.DirectorySeparatorChar, comparison))
        {
            throw new CoverageRunArtifactContractException("escaping", "artifact escaped the invocation directory");
        }

        for (var path = candidatePath; path.Length >= rootPath.Length; path = Path.GetDirectoryName(path) ?? string.Empty)
        {
            if ((File.GetAttributes(path) & FileAttributes.ReparsePoint) != 0)
            {
                throw new CoverageRunArtifactContractException("escaping", "symbolic link or reparse point encountered");
            }

            if (string.Equals(path, rootPath, comparison))
            {
                break;
            }
        }
    }

    private static bool IsOwnedCollectorJoinedArgument(string value)
    {
        var prefixes = new[]
        {
            "--collect:", "--collect=", "--results-directory:", "--results-directory=",
        };
        return prefixes.Any(prefix => value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsOwnedMsbuildPropertyArgument(string value)
    {
        var propertyPrefixes = new[] { "/p:", "-p:", "/property:", "-property:", "--property:" };
        var prefix = propertyPrefixes.FirstOrDefault(candidate => value.StartsWith(candidate, StringComparison.OrdinalIgnoreCase));
        if (prefix is null)
        {
            return false;
        }

        var ownedProperties = new[]
        {
            "CollectCoverage",
            "Include",
            "IncludeDirectory",
            "Exclude",
            "ExcludeByFile",
            "ExcludeByAttribute",
            "IncludeTestAssembly",
            "SingleHit",
            "MergeWith",
            "UseSourceLink",
            "SkipAutoProps",
            "DeterministicReport",
            "DoesNotReturnAttribute",
            "ExcludeAssembliesWithoutSources",
            "DisableManagedInstrumentationRestore",
            "CoverletOutputFormat",
            "CoverletOutput",
            "Threshold",
            "ThresholdType",
            "ThresholdStat",
        };
        return value[prefix.Length..]
            .Split([';', ','], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(property => property.Split('=', 2)[0])
            .Any(name => ownedProperties.Contains(name, StringComparer.OrdinalIgnoreCase));
    }

    private static bool IsOwnedCollectorSplitArgument(string value)
        => string.Equals(value, "--collect", StringComparison.OrdinalIgnoreCase)
            || string.Equals(value, "--results-directory", StringComparison.OrdinalIgnoreCase);

    private static bool IsSettingsArgument(string value)
        => string.Equals(value, "--settings", StringComparison.OrdinalIgnoreCase)
            || string.Equals(value, "-s", StringComparison.OrdinalIgnoreCase)
            || value.StartsWith("--settings:", StringComparison.OrdinalIgnoreCase)
            || value.StartsWith("--settings=", StringComparison.OrdinalIgnoreCase);

    private static StringComparer GetPathComparer()
        => OperatingSystem.IsWindows() || OperatingSystem.IsMacOS() ? StringComparer.OrdinalIgnoreCase : StringComparer.Ordinal;

    private static Exception ArtifactFailure(string logFile, string rawDirectory, string cause)
        => CoverageRunDiagnostics.Create(
            "ASCOV115",
            "Coverage driver artifact contract failed.",
            $"{cause}. Raw results: {rawDirectory}.",
            "Inspect the project log and raw collector results, then rerun coverage run.",
            "Cli/ForgeTrust.AppSurface.Cli/README.md#coverage-run-diagnostics",
            logFile);

    /// <summary>
    /// Creates the stable artifact-contract diagnostic used by workflow-level failure ordering.
    /// </summary>
    /// <param name="logFile">Project log path included in the diagnostic.</param>
    /// <param name="rawDirectory">Raw or canonical artifact directory that failed validation.</param>
    /// <param name="cause">Stable artifact failure detail.</param>
    /// <returns>An <c>ASCOV115</c> command failure.</returns>
    internal static Exception CreateArtifactFailure(string logFile, string rawDirectory, string cause)
        => ArtifactFailure(logFile, rawDirectory, cause);

    private sealed class CoverageRunArtifactContractException(string status, string cause) : Exception(cause)
    {
        public string Status { get; } = status;
        public string Cause { get; } = cause;
    }
}
