<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddTailwindBuildTaskFilesToPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Import Project="Tailwind.Common.props" />

  <ItemGroup>
    <Compile Remove="runtimes/**" />
    <EmbeddedResource Remove="runtimes/**" />
    <None Remove="runtimes/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" />
    <ProjectReference Include="../../ForgeTrust.AppSurface.Core/ForgeTrust.AppSurface.Core.csproj" />
    <ProjectReference Include="../ForgeTrust.AppSurface.Web.Tailwind.Tasks/ForgeTrust.AppSurface.Web.Tailwind.Tasks.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <!-- This allows the targets file to be bundled in the NuGet package -->
  <ItemGroup>
    <EmbeddedResource Include="tailwind.release.json" />
    <None Include="build\ForgeTrust.AppSurface.Web.Tailwind.targets" Pack="true" PackagePath="build" />
    <None Include="tailwind.release.json" Pack="true" PackagePath="build" />
    <None Include="tailwind.version" Pack="true" PackagePath="build" />
    <None Include="$(MSBuildProjectDirectory)\THIRD-PARTY-NOTICES.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="AddTailwindBuildTaskFilesToPackage">
    <ItemGroup>
      <TfmSpecificPackageFile Include="..\ForgeTrust.AppSurface.Web.Tailwind.Tasks\bin\$(Configuration)\net10.0\*.dll" PackagePath="build\tasks" />
      <TfmSpecificPackageFile Include="..\ForgeTrust.AppSurface.Web.Tailwind.Tasks\bin\$(Configuration)\net10.0\*.deps.json" PackagePath="build\tasks" />
    </ItemGroup>
  </Target>
</Project>
